export const monthNames = [
  "January",
  "February",
  "March",
  "April",
  "May",
  "June",
  "July",
  "August",
  "September",
  "October",
  "November",
  "December",
];

export const sitting = ["Yes", "No"];
export const gender = ["Male", "Female"];
export const olevel = [
  "WAEC",
  "NECO",
  "WAEC & NECO",
  "WAEC & WAEC",
  "NECO & NECO",
];

export const universities = [
  "Abia State University",
  "Abubakar Tafawa Balewa University",
  "Adamawa State University",
  "Adekunle Ajasin University",
  "Ahmadu Bello University",
  "Air Force Institute of Technology",
  "Akwa Ibom State University",
  "Alex Ekwueme Federal University Ndufu-Alike",
  "Ambrose Alli University",
  "Bauchi State University",
  "Bayero University",
  "Bayelsa Medical University",
  "Benue State University",
  "Borno State University",
  "Chukwuemeka Odumegwu Ojukwu University",
  "Delta State University",
  "Delta State University of Science and Technology",
  "Dennis Osadebay University",
  "Ebonyi State University",
  "Edo State University Uzairue",
  "Ekiti State University",
  "Enugu State University of Science and Technology",
  "Federal University Dutse",
  "Federal University Dutsin-Ma",
  "Federal University Gashua",
  "Federal University Kashere",
  "Federal University Lafia",
  "Federal University Lokoja",
  "Federal University of Agriculture Abeokuta",
  "Federal University of Agriculture Makurdi",
  "Federal University of Technology Akure",
  "Federal University of Technology Minna",
  "Federal University of Technology Owerri",
  "Federal University Otuoke",
  "Federal University Oye-Ekiti",
  "Federal University Wukari",
  "Gombe State University",
  "Ibrahim Badamasi Babangida University",
  "Ignatius Ajuru University of Education",
  "Imo State University",
  "Kaduna State University",
  "Kebbi State University of Science and Technology",
  "Kingsley Ozumba Mbadiwe University",
  "Kwara State University",
  "Ladoke Akintola University of Technology",
  "Lagos State University",
  "Michael Okpara University of Agriculture",
  "Nasarawa State University",
  "Niger Delta University",
  "Nigeria Maritime University",
  "Nigerian Army University Biu",
  "Nigerian Defence Academy",
  "Nigeria Police Academy",
  "Obafemi Awolowo University",
  "Olabisi Onabanjo University",
  "Olusegun Agagu University of Science and Technology",
  "Osun State University",
  "Plateau State University",
  "Prince Abubakar Audu University",
  "Rivers State University",
  "Sokoto State University",
  "Sule Lamido University",
  "Taraba State University",
  "Umaru Musa Yar’adua University",
  "University of Benin",
  "University of Calabar",
  "University of Cross River State",
  "University of Delta",
  "University of Ibadan",
  "University of Ilorin",
  "University of Jos",
  "University of Lagos",
  "University of Maiduguri",
  "University of Nigeria",
  "University of Port Harcourt",
  "Usmanu Danfodiyo University",
  "Yobe State University",
  "Yusuf Maitama Sule University Kano",
  "Zamfara State University",
];
